spring:
  data:
    mongodb:
      uri: ${MONGO_URI:"mongodb://localhost:27017/Cars"}

mongo-change-stream:
  collectionName: ${COLLECTION_NAME:"Cars"}
  operation-types: ${OPERATION_TYPES:"insert, update, delete"}
